<?php

namespace Plugins;
use Yii;


class PinpointYiiClassLoader
{
    /**
     * copy from yii autoload
     */
    public static function findFile($className)
    {
        if (isset(Yii::$classMap[$className])) {
            $classFile = Yii::$classMap[$className];
            if ($classFile[0] === '@') {
                $classFile = Yii::getAlias($classFile);
            }
        } elseif (strpos($className, '\\') !== false) {
            $classFile = Yii::getAlias('@' . str_replace('\\', '/', $className) . '.php', false);
            if ($classFile === false || !is_file($classFile)) {
                return null;
            }
        } else {
            return null;
        }
         return $classFile;
    }

    public static function autoload($className)
    {
        Yii::autoload($className); // TODO: Change the autogenerated stub
    }
}
