language: php

php:
- 7.1

git:
  submodules: false

sudo : required

env:
  - ROOT=$PWD

addons:
  apt:
    sources:
    - sourceline: 'ppa:rexut/factory'
    - ubuntu-toolchain-r-test
    packages:
    - boost1.63
    - nginx

before_install:
- sudo apt-get install -yqq automake bison flex git libevent-dev libssl-dev libtool make pkg-config
- sudo apt-get install -yqq libpcre3 libpcre3-dev
- sudo apt-get install -yqq zlib1g-dev

install:
- wget http://cn2.php.net/distributions/php-5.6.31.tar.gz
- wget http://apache.fayea.com/thrift/0.11.0/thrift-0.11.0.tar.gz
- tar zxvf php-5.6.31.tar.gz 1>/dev/zero
- tar -zxvf thrift-0.11.0.tar.gz 1>/dev/zero
- cd thrift-0.11.0
- ./configure --prefix=/usr CXXFLAGS=-DFORCE_BOOST_SMART_PTR --enable-tests=no --with-cpp --with-php=no --with-python=no --with-ruby=no --with-nodejs=no --with-qt4=no --with-java=no --with-boost=/usr --with-boost-libdir=/usr/lib 1>/dev/zero
- sudo make -j4 1>/dev/zero && sudo make install
- export WITH_THRIFT_PATH=/usr
- export WITH_BOOST_PATH=/usr
- cd ../php-5.6.31
- ./configure --prefix=/home/travis/php --enable-fpm --with-libxml-dir --with-gd --with-jpeg-dir --with-curl --with-png-dir --with-freetype-dir --with-iconv-dir --with-bz2 --with-pdo-mysql --enable-mysqlnd --with-mysqli --enable-soap --enable-ftp --enable-mbstring --enable-sockets --enable-exif --enable-debug 1>/dev/zero
- make && make install 1>/dev/zero
- ulimit -c unlimited
- cd ../
- mkdir -p simulate/log
- mkdir -p simulate/tmp
- cp simulate/conf/fastcgi_params simulate/tmp/
- cd pinpoint_common && make thrift && cd ..
- export PATH=/home/travis/php/bin:/home/travis/php/sbin:/home/travis/nginx/sbin:$PATH
- export PKG_CONFIG_PATH=/usr/lib:/usr/lib/pkgconfig:$PKG_CONFIG_PATH
- export LD_LIBRARY_PATH=/usr/lib:$LD_LIBRARY_PATH
- export PINPOINT_CXXFLAG='-DTEST_SIMULATE'
- export PINPOINT_CFLAG='-DTEST_SIMULATE'

script:
# - cd $ROOT/test/ && make && ./pinpoint_unittest && make clean
- cd $ROOT/simulate/shell && echo "run python run_test.py" && python run_test.py ../conf/php_test_conf_ci.json 
