services:
  dev-mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_TCP_PORT: 3306  
    ports:
      - '33060:3306' 
    volumes:
      - ..:/workspace:cached
       
    healthcheck:
      test: ["CMD", "mysqladmin","-uroot","-ppassword" ,"ping", "-h", "localhost"]
      interval: 15s
      timeout: 10s
      retries: 10
  
  dev-mysql-setup:
    image: mysql:5.7 
    depends_on:
      dev-mysql:
        condition: service_healthy
    volumes:
      - ..:/workspace:cached    
    # todo load all data 
    entrypoint: [ "bash", "-c", "cd /workspace/testapps/ && sh load_sample_db.sh"]

  redis:
    image: redis:alpine
    command: redis-server --port 6379
    depends_on:
      dev-mysql-setup:
        condition: service_completed_successfully
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6389:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 1s
      retries: 1

  testapp-flask:
    container_name: flask
    depends_on:
      redis:
        condition: service_healthy
    restart: always
    build:
      dockerfile: testapps/flask.dockerfile
      context: ../
    ports:
      - 8184:80

    healthcheck:
      test: curl -f http://testapp-flask
      interval: 5s 
      timeout: 1s       

  testapp-php:
    container_name: yii2
    depends_on:
      redis:
        condition: service_healthy
    restart: always
    build:
      dockerfile: testapps/php.dockerfile
      context: ../
    ports:
      - 8185:80

    healthcheck:
      test: curl -f http://testapp-php
      interval: 5s 
      timeout: 1s       

  testapp-fastapi:
    container_name: fastapi
    depends_on:
      redis:
        condition: service_healthy    
    restart: always
    build:
      dockerfile: testapps/fastapi.dockerfile
      context: ../
    ports:
      - 8186:8000
    healthcheck:
      test: curl -f http://testapp-fastapi:8000
      interval: 5s 
      timeout: 1s        

  # test call self
  backend:
    restart: always
    container_name: backend
    depends_on:
      redis:
        condition: service_healthy    
    build:
      dockerfile: testapps/backend.dockerfile
      context: ../
    ports:
      - 8187:80  

    healthcheck:
      test: curl -f http://backend
      interval: 5s 
      timeout: 1s       
  
  testapp-django:
    container_name: django
    depends_on:
      redis:
        condition: service_healthy    
    restart: always
    build:
      dockerfile: testapps/django.dockerfile
      context: ../
    ports:
      - 8188:8000  
    healthcheck:
      test: curl -f http://testapp-django:8000/polls
      interval: 5s 
      timeout: 1s     

  httpbin:
    build:
      dockerfile: testapps/httpbin.dockerfile
      context: ../
    restart: always
    healthcheck:
      test: curl -f http://httpbin
      interval: 5s
      timeout: 10s
      retries: 50
    
  dev-collector:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ../collector-agent/

    environment:
      - PP_COLLECTOR_AGENT_SPAN_IP=dev-pinpoint
      - PP_COLLECTOR_AGENT_SPAN_PORT=9993
      - PP_COLLECTOR_AGENT_AGENT_IP=dev-pinpoint
      - PP_COLLECTOR_AGENT_AGENT_PORT=9991
      - PP_COLLECTOR_AGENT_STAT_IP=dev-pinpoint
      - PP_COLLECTOR_AGENT_STAT_PORT=9992
      - PP_COLLECTOR_AGENT_ISDOCKER=true
      - PP_Log_Level=DEBUG
      - PP_ADDRESS=0.0.0.0@10000
    ports:
      - 10000:10000

  mongodb:
    image: 'mongo'
    restart: always
    hostname: mongodb
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
    # ports:
      # - 27017:27017

  python-plugins:
    build:
      dockerfile: testapps/python-plugins.dockerfile
      context: ../     
    profiles:
      - testing
    depends_on:
      redis:
        condition: service_healthy
      httpbin:
        condition: service_healthy
      mongodb:
        condition: service_healthy