services:
  dev-mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_TCP_PORT: 3306  
    ports:
      - '33060:3306' 
  dev-mysql-setup:
    image: mysql:5.7 
    depends_on:
      dev-mysql:
        condition: service_completed_successfully
    # restart: "always"      
    entrypoint: [ "bash", "-c", "cd /app/ && mysql -uroot -ppassword -hdev-mysql <employees.sql"]
    volumes:
      - "./test_db:/app/"
  
  testapp-php:
    restart: always
    build:
      dockerfile: testapps/php.dockerfile
      context: ../
    ports:
      - 8185:80
      
  redis:
    image: redis:alpine
    command: redis-server --port 6379
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6389:6379

  testapp-flask:
    restart: always
    build:
      dockerfile: flask.dockerfile
    ports:
      - 8184:80
    
  dev-collector:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ../collector-agent/

    environment:
      - PP_COLLECTOR_AGENT_SPAN_IP=dev-pinpoint
      - PP_COLLECTOR_AGENT_SPAN_PORT=9993
      - PP_COLLECTOR_AGENT_AGENT_IP=dev-pinpoint
      - PP_COLLECTOR_AGENT_AGENT_PORT=9991
      - PP_COLLECTOR_AGENT_STAT_IP=dev-pinpoint
      - PP_COLLECTOR_AGENT_STAT_PORT=9992
      - PP_COLLECTOR_AGENT_ISDOCKER=true
      - PP_Log_Level=DEBUG
      - PP_ADDRESS=0.0.0.0@10000
    ports:
      - 10000:10000