# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import Span_pb2 as Span__pb2
import Stat_pb2 as Stat__pb2
import ThreadDump_pb2 as ThreadDump__pb2
import Cmd_pb2 as Cmd__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Service.proto',
  package='v1',
  syntax='proto3',
  serialized_options=_b('\n!com.navercorp.pinpoint.grpc.traceB\014ServiceProtoP\001'),
  serialized_pb=_b('\n\rService.proto\x12\x02v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\nSpan.proto\x1a\nStat.proto\x1a\x10ThreadDump.proto\x1a\tCmd.proto2@\n\x04Span\x12\x38\n\x08SendSpan\x12\x10.v1.PSpanMessage\x1a\x16.google.protobuf.Empty\"\x00(\x01\x32\x65\n\x05\x41gent\x12\x31\n\x10RequestAgentInfo\x12\x0e.v1.PAgentInfo\x1a\x0b.v1.PResult\"\x00\x12)\n\x0bPingSession\x12\t.v1.PPing\x1a\t.v1.PPing\"\x00(\x01\x30\x01\x32\xb5\x01\n\x08Metadata\x12\x35\n\x12RequestSqlMetaData\x12\x10.v1.PSqlMetaData\x1a\x0b.v1.PResult\"\x00\x12\x35\n\x12RequestApiMetaData\x12\x10.v1.PApiMetaData\x1a\x0b.v1.PResult\"\x00\x12;\n\x15RequestStringMetaData\x12\x13.v1.PStringMetaData\x1a\x0b.v1.PResult\"\x00\x32\x45\n\x04Stat\x12=\n\rSendAgentStat\x12\x10.v1.PStatMessage\x1a\x16.google.protobuf.Empty\"\x00(\x01\x32\x9a\x03\n\x16ProfilerCommandService\x12\x37\n\rHandleCommand\x12\x0f.v1.PCmdMessage\x1a\x0f.v1.PCmdRequest\"\x00(\x01\x30\x01\x12=\n\x0b\x43ommandEcho\x12\x14.v1.PCmdEchoResponse\x1a\x16.google.protobuf.Empty\"\x00\x12Z\n\x1e\x43ommandStreamActiveThreadCount\x12\x1c.v1.PCmdActiveThreadCountRes\x1a\x16.google.protobuf.Empty\"\x00(\x01\x12P\n\x17\x43ommandActiveThreadDump\x12\x1b.v1.PCmdActiveThreadDumpRes\x1a\x16.google.protobuf.Empty\"\x00\x12Z\n\x1c\x43ommandActiveThreadLightDump\x12 .v1.PCmdActiveThreadLightDumpRes\x1a\x16.google.protobuf.Empty\"\x00\x42\x33\n!com.navercorp.pinpoint.grpc.traceB\x0cServiceProtoP\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,Span__pb2.DESCRIPTOR,Stat__pb2.DESCRIPTOR,ThreadDump__pb2.DESCRIPTOR,Cmd__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_SPAN = _descriptor.ServiceDescriptor(
  name='Span',
  full_name='v1.Span',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=103,
  serialized_end=167,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendSpan',
    full_name='v1.Span.SendSpan',
    index=0,
    containing_service=None,
    input_type=Span__pb2._PSPANMESSAGE,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SPAN)

DESCRIPTOR.services_by_name['Span'] = _SPAN


_AGENT = _descriptor.ServiceDescriptor(
  name='Agent',
  full_name='v1.Agent',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=169,
  serialized_end=270,
  methods=[
  _descriptor.MethodDescriptor(
    name='RequestAgentInfo',
    full_name='v1.Agent.RequestAgentInfo',
    index=0,
    containing_service=None,
    input_type=Stat__pb2._PAGENTINFO,
    output_type=Span__pb2._PRESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='PingSession',
    full_name='v1.Agent.PingSession',
    index=1,
    containing_service=None,
    input_type=Stat__pb2._PPING,
    output_type=Stat__pb2._PPING,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_AGENT)

DESCRIPTOR.services_by_name['Agent'] = _AGENT


_METADATA = _descriptor.ServiceDescriptor(
  name='Metadata',
  full_name='v1.Metadata',
  file=DESCRIPTOR,
  index=2,
  serialized_options=None,
  serialized_start=273,
  serialized_end=454,
  methods=[
  _descriptor.MethodDescriptor(
    name='RequestSqlMetaData',
    full_name='v1.Metadata.RequestSqlMetaData',
    index=0,
    containing_service=None,
    input_type=Span__pb2._PSQLMETADATA,
    output_type=Span__pb2._PRESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RequestApiMetaData',
    full_name='v1.Metadata.RequestApiMetaData',
    index=1,
    containing_service=None,
    input_type=Span__pb2._PAPIMETADATA,
    output_type=Span__pb2._PRESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RequestStringMetaData',
    full_name='v1.Metadata.RequestStringMetaData',
    index=2,
    containing_service=None,
    input_type=Span__pb2._PSTRINGMETADATA,
    output_type=Span__pb2._PRESULT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_METADATA)

DESCRIPTOR.services_by_name['Metadata'] = _METADATA


_STAT = _descriptor.ServiceDescriptor(
  name='Stat',
  full_name='v1.Stat',
  file=DESCRIPTOR,
  index=3,
  serialized_options=None,
  serialized_start=456,
  serialized_end=525,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendAgentStat',
    full_name='v1.Stat.SendAgentStat',
    index=0,
    containing_service=None,
    input_type=Stat__pb2._PSTATMESSAGE,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_STAT)

DESCRIPTOR.services_by_name['Stat'] = _STAT


_PROFILERCOMMANDSERVICE = _descriptor.ServiceDescriptor(
  name='ProfilerCommandService',
  full_name='v1.ProfilerCommandService',
  file=DESCRIPTOR,
  index=4,
  serialized_options=None,
  serialized_start=528,
  serialized_end=938,
  methods=[
  _descriptor.MethodDescriptor(
    name='HandleCommand',
    full_name='v1.ProfilerCommandService.HandleCommand',
    index=0,
    containing_service=None,
    input_type=Cmd__pb2._PCMDMESSAGE,
    output_type=Cmd__pb2._PCMDREQUEST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CommandEcho',
    full_name='v1.ProfilerCommandService.CommandEcho',
    index=1,
    containing_service=None,
    input_type=Cmd__pb2._PCMDECHORESPONSE,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CommandStreamActiveThreadCount',
    full_name='v1.ProfilerCommandService.CommandStreamActiveThreadCount',
    index=2,
    containing_service=None,
    input_type=Cmd__pb2._PCMDACTIVETHREADCOUNTRES,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CommandActiveThreadDump',
    full_name='v1.ProfilerCommandService.CommandActiveThreadDump',
    index=3,
    containing_service=None,
    input_type=Cmd__pb2._PCMDACTIVETHREADDUMPRES,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CommandActiveThreadLightDump',
    full_name='v1.ProfilerCommandService.CommandActiveThreadLightDump',
    index=4,
    containing_service=None,
    input_type=Cmd__pb2._PCMDACTIVETHREADLIGHTDUMPRES,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PROFILERCOMMANDSERVICE)

DESCRIPTOR.services_by_name['ProfilerCommandService'] = _PROFILERCOMMANDSERVICE

# @@protoc_insertion_point(module_scope)
