/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Command_CONSTANTS_H
#define Command_CONSTANTS_H

#include "Command_types.h"



class CommandConstants {
 public:
  CommandConstants();

};

extern const CommandConstants g_Command_constants;



#endif
