/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Pinpoint_CONSTANTS_H
#define Pinpoint_CONSTANTS_H

#include "Pinpoint_types.h"



class PinpointConstants {
 public:
  PinpointConstants();

};

extern const PinpointConstants g_Pinpoint_constants;



#endif
