/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Trace_CONSTANTS_H
#define Trace_CONSTANTS_H

#include "Trace_types.h"



class TraceConstants {
 public:
  TraceConstants();

};

extern const TraceConstants g_Trace_constants;



#endif
