// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Span.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PSpanMessage struct {
	// Types that are valid to be assigned to Field:
	//	*PSpanMessage_Span
	//	*PSpanMessage_SpanChunk
	Field                isPSpanMessage_Field `protobuf_oneof:"field"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PSpanMessage) Reset()         { *m = PSpanMessage{} }
func (m *PSpanMessage) String() string { return proto.CompactTextString(m) }
func (*PSpanMessage) ProtoMessage()    {}
func (*PSpanMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_72a7884ce2d4c43e, []int{0}
}

func (m *PSpanMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PSpanMessage.Unmarshal(m, b)
}
func (m *PSpanMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PSpanMessage.Marshal(b, m, deterministic)
}
func (m *PSpanMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PSpanMessage.Merge(m, src)
}
func (m *PSpanMessage) XXX_Size() int {
	return xxx_messageInfo_PSpanMessage.Size(m)
}
func (m *PSpanMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PSpanMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PSpanMessage proto.InternalMessageInfo

type isPSpanMessage_Field interface {
	isPSpanMessage_Field()
}

type PSpanMessage_Span struct {
	Span *PSpan `protobuf:"bytes,1,opt,name=span,proto3,oneof"`
}

type PSpanMessage_SpanChunk struct {
	SpanChunk *PSpanChunk `protobuf:"bytes,2,opt,name=spanChunk,proto3,oneof"`
}

func (*PSpanMessage_Span) isPSpanMessage_Field() {}

func (*PSpanMessage_SpanChunk) isPSpanMessage_Field() {}

func (m *PSpanMessage) GetField() isPSpanMessage_Field {
	if m != nil {
		return m.Field
	}
	return nil
}

func (m *PSpanMessage) GetSpan() *PSpan {
	if x, ok := m.GetField().(*PSpanMessage_Span); ok {
		return x.Span
	}
	return nil
}

func (m *PSpanMessage) GetSpanChunk() *PSpanChunk {
	if x, ok := m.GetField().(*PSpanMessage_SpanChunk); ok {
		return x.SpanChunk
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*PSpanMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*PSpanMessage_Span)(nil),
		(*PSpanMessage_SpanChunk)(nil),
	}
}

type PSpan struct {
	Version       int32           `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	TransactionId *PTransactionId `protobuf:"bytes,2,opt,name=transactionId,proto3" json:"transactionId,omitempty"`
	SpanId        int64           `protobuf:"fixed64,3,opt,name=spanId,proto3" json:"spanId,omitempty"`
	ParentSpanId  int64           `protobuf:"fixed64,4,opt,name=parentSpanId,proto3" json:"parentSpanId,omitempty"`
	// span event's startTimestamp
	StartTime              int64            `protobuf:"varint,5,opt,name=startTime,proto3" json:"startTime,omitempty"`
	Elapsed                int32            `protobuf:"varint,6,opt,name=elapsed,proto3" json:"elapsed,omitempty"`
	ApiId                  int32            `protobuf:"varint,7,opt,name=apiId,proto3" json:"apiId,omitempty"`
	ServiceType            int32            `protobuf:"varint,8,opt,name=serviceType,proto3" json:"serviceType,omitempty"`
	AcceptEvent            *PAcceptEvent    `protobuf:"bytes,9,opt,name=acceptEvent,proto3" json:"acceptEvent,omitempty"`
	Annotation             []*PAnnotation   `protobuf:"bytes,10,rep,name=annotation,proto3" json:"annotation,omitempty"`
	Flag                   int32            `protobuf:"varint,11,opt,name=flag,proto3" json:"flag,omitempty"`
	Err                    int32            `protobuf:"zigzag32,12,opt,name=err,proto3" json:"err,omitempty"`
	SpanEvent              []*PSpanEvent    `protobuf:"bytes,13,rep,name=spanEvent,proto3" json:"spanEvent,omitempty"`
	ExceptionInfo          *PIntStringValue `protobuf:"bytes,14,opt,name=exceptionInfo,proto3" json:"exceptionInfo,omitempty"`
	ApplicationServiceType int32            `protobuf:"varint,15,opt,name=applicationServiceType,proto3" json:"applicationServiceType,omitempty"`
	LoggingTransactionInfo int32            `protobuf:"varint,16,opt,name=loggingTransactionInfo,proto3" json:"loggingTransactionInfo,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}         `json:"-"`
	XXX_unrecognized       []byte           `json:"-"`
	XXX_sizecache          int32            `json:"-"`
}

func (m *PSpan) Reset()         { *m = PSpan{} }
func (m *PSpan) String() string { return proto.CompactTextString(m) }
func (*PSpan) ProtoMessage()    {}
func (*PSpan) Descriptor() ([]byte, []int) {
	return fileDescriptor_72a7884ce2d4c43e, []int{1}
}

func (m *PSpan) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PSpan.Unmarshal(m, b)
}
func (m *PSpan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PSpan.Marshal(b, m, deterministic)
}
func (m *PSpan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PSpan.Merge(m, src)
}
func (m *PSpan) XXX_Size() int {
	return xxx_messageInfo_PSpan.Size(m)
}
func (m *PSpan) XXX_DiscardUnknown() {
	xxx_messageInfo_PSpan.DiscardUnknown(m)
}

var xxx_messageInfo_PSpan proto.InternalMessageInfo

func (m *PSpan) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *PSpan) GetTransactionId() *PTransactionId {
	if m != nil {
		return m.TransactionId
	}
	return nil
}

func (m *PSpan) GetSpanId() int64 {
	if m != nil {
		return m.SpanId
	}
	return 0
}

func (m *PSpan) GetParentSpanId() int64 {
	if m != nil {
		return m.ParentSpanId
	}
	return 0
}

func (m *PSpan) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *PSpan) GetElapsed() int32 {
	if m != nil {
		return m.Elapsed
	}
	return 0
}

func (m *PSpan) GetApiId() int32 {
	if m != nil {
		return m.ApiId
	}
	return 0
}

func (m *PSpan) GetServiceType() int32 {
	if m != nil {
		return m.ServiceType
	}
	return 0
}

func (m *PSpan) GetAcceptEvent() *PAcceptEvent {
	if m != nil {
		return m.AcceptEvent
	}
	return nil
}

func (m *PSpan) GetAnnotation() []*PAnnotation {
	if m != nil {
		return m.Annotation
	}
	return nil
}

func (m *PSpan) GetFlag() int32 {
	if m != nil {
		return m.Flag
	}
	return 0
}

func (m *PSpan) GetErr() int32 {
	if m != nil {
		return m.Err
	}
	return 0
}

func (m *PSpan) GetSpanEvent() []*PSpanEvent {
	if m != nil {
		return m.SpanEvent
	}
	return nil
}

func (m *PSpan) GetExceptionInfo() *PIntStringValue {
	if m != nil {
		return m.ExceptionInfo
	}
	return nil
}

func (m *PSpan) GetApplicationServiceType() int32 {
	if m != nil {
		return m.ApplicationServiceType
	}
	return 0
}

func (m *PSpan) GetLoggingTransactionInfo() int32 {
	if m != nil {
		return m.LoggingTransactionInfo
	}
	return 0
}

type PTransactionId struct {
	// identical to agentId if null
	AgentId              string   `protobuf:"bytes,1,opt,name=agentId,proto3" json:"agentId,omitempty"`
	AgentStartTime       int64    `protobuf:"varint,2,opt,name=agentStartTime,proto3" json:"agentStartTime,omitempty"`
	Sequence             int64    `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PTransactionId) Reset()         { *m = PTransactionId{} }
func (m *PTransactionId) String() string { return proto.CompactTextString(m) }
func (*PTransactionId) ProtoMessage()    {}
func (*PTransactionId) Descriptor() ([]byte, []int) {
	return fileDescriptor_72a7884ce2d4c43e, []int{2}
}

func (m *PTransactionId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PTransactionId.Unmarshal(m, b)
}
func (m *PTransactionId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PTransactionId.Marshal(b, m, deterministic)
}
func (m *PTransactionId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PTransactionId.Merge(m, src)
}
func (m *PTransactionId) XXX_Size() int {
	return xxx_messageInfo_PTransactionId.Size(m)
}
func (m *PTransactionId) XXX_DiscardUnknown() {
	xxx_messageInfo_PTransactionId.DiscardUnknown(m)
}

var xxx_messageInfo_PTransactionId proto.InternalMessageInfo

func (m *PTransactionId) GetAgentId() string {
	if m != nil {
		return m.AgentId
	}
	return ""
}

func (m *PTransactionId) GetAgentStartTime() int64 {
	if m != nil {
		return m.AgentStartTime
	}
	return 0
}

func (m *PTransactionId) GetSequence() int64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

type PAcceptEvent struct {
	Rpc                  string       `protobuf:"bytes,1,opt,name=rpc,proto3" json:"rpc,omitempty"`
	EndPoint             string       `protobuf:"bytes,2,opt,name=endPoint,proto3" json:"endPoint,omitempty"`
	RemoteAddr           string       `protobuf:"bytes,3,opt,name=remoteAddr,proto3" json:"remoteAddr,omitempty"`
	ParentInfo           *PParentInfo `protobuf:"bytes,4,opt,name=parentInfo,proto3" json:"parentInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PAcceptEvent) Reset()         { *m = PAcceptEvent{} }
func (m *PAcceptEvent) String() string { return proto.CompactTextString(m) }
func (*PAcceptEvent) ProtoMessage()    {}
func (*PAcceptEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_72a7884ce2d4c43e, []int{3}
}

func (m *PAcceptEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PAcceptEvent.Unmarshal(m, b)
}
func (m *PAcceptEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PAcceptEvent.Marshal(b, m, deterministic)
}
func (m *PAcceptEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PAcceptEvent.Merge(m, src)
}
func (m *PAcceptEvent) XXX_Size() int {
	return xxx_messageInfo_PAcceptEvent.Size(m)
}
func (m *PAcceptEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_PAcceptEvent.DiscardUnknown(m)
}

var xxx_messageInfo_PAcceptEvent proto.InternalMessageInfo

func (m *PAcceptEvent) GetRpc() string {
	if m != nil {
		return m.Rpc
	}
	return ""
}

func (m *PAcceptEvent) GetEndPoint() string {
	if m != nil {
		return m.EndPoint
	}
	return ""
}

func (m *PAcceptEvent) GetRemoteAddr() string {
	if m != nil {
		return m.RemoteAddr
	}
	return ""
}

func (m *PAcceptEvent) GetParentInfo() *PParentInfo {
	if m != nil {
		return m.ParentInfo
	}
	return nil
}

type PParentInfo struct {
	ParentApplicationName string   `protobuf:"bytes,1,opt,name=parentApplicationName,proto3" json:"parentApplicationName,omitempty"`
	ParentApplicationType int32    `protobuf:"varint,2,opt,name=parentApplicationType,proto3" json:"parentApplicationType,omitempty"`
	AcceptorHost          string   `protobuf:"bytes,3,opt,name=acceptorHost,proto3" json:"acceptorHost,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *PParentInfo) Reset()         { *m = PParentInfo{} }
func (m *PParentInfo) String() string { return proto.CompactTextString(m) }
func (*PParentInfo) ProtoMessage()    {}
func (*PParentInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_72a7884ce2d4c43e, []int{4}
}

func (m *PParentInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PParentInfo.Unmarshal(m, b)
}
func (m *PParentInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PParentInfo.Marshal(b, m, deterministic)
}
func (m *PParentInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PParentInfo.Merge(m, src)
}
func (m *PParentInfo) XXX_Size() int {
	return xxx_messageInfo_PParentInfo.Size(m)
}
func (m *PParentInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PParentInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PParentInfo proto.InternalMessageInfo

func (m *PParentInfo) GetParentApplicationName() string {
	if m != nil {
		return m.ParentApplicationName
	}
	return ""
}

func (m *PParentInfo) GetParentApplicationType() int32 {
	if m != nil {
		return m.ParentApplicationType
	}
	return 0
}

func (m *PParentInfo) GetAcceptorHost() string {
	if m != nil {
		return m.AcceptorHost
	}
	return ""
}

type PLocalAsyncId struct {
	AsyncId              int32    `protobuf:"varint,1,opt,name=asyncId,proto3" json:"asyncId,omitempty"`
	Sequence             int32    `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PLocalAsyncId) Reset()         { *m = PLocalAsyncId{} }
func (m *PLocalAsyncId) String() string { return proto.CompactTextString(m) }
func (*PLocalAsyncId) ProtoMessage()    {}
func (*PLocalAsyncId) Descriptor() ([]byte, []int) {
	return fileDescriptor_72a7884ce2d4c43e, []int{5}
}

func (m *PLocalAsyncId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PLocalAsyncId.Unmarshal(m, b)
}
func (m *PLocalAsyncId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PLocalAsyncId.Marshal(b, m, deterministic)
}
func (m *PLocalAsyncId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PLocalAsyncId.Merge(m, src)
}
func (m *PLocalAsyncId) XXX_Size() int {
	return xxx_messageInfo_PLocalAsyncId.Size(m)
}
func (m *PLocalAsyncId) XXX_DiscardUnknown() {
	xxx_messageInfo_PLocalAsyncId.DiscardUnknown(m)
}

var xxx_messageInfo_PLocalAsyncId proto.InternalMessageInfo

func (m *PLocalAsyncId) GetAsyncId() int32 {
	if m != nil {
		return m.AsyncId
	}
	return 0
}

func (m *PLocalAsyncId) GetSequence() int32 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

type PSpanEvent struct {
	Sequence             int32            `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Depth                int32            `protobuf:"varint,2,opt,name=depth,proto3" json:"depth,omitempty"`
	StartElapsed         int32            `protobuf:"varint,3,opt,name=startElapsed,proto3" json:"startElapsed,omitempty"`
	EndElapsed           int32            `protobuf:"varint,4,opt,name=endElapsed,proto3" json:"endElapsed,omitempty"`
	ServiceType          int32            `protobuf:"zigzag32,5,opt,name=serviceType,proto3" json:"serviceType,omitempty"`
	Annotation           []*PAnnotation   `protobuf:"bytes,6,rep,name=annotation,proto3" json:"annotation,omitempty"`
	ApiId                int32            `protobuf:"zigzag32,10,opt,name=apiId,proto3" json:"apiId,omitempty"`
	ExceptionInfo        *PIntStringValue `protobuf:"bytes,11,opt,name=exceptionInfo,proto3" json:"exceptionInfo,omitempty"`
	NextEvent            *PNextEvent      `protobuf:"bytes,12,opt,name=nextEvent,proto3" json:"nextEvent,omitempty"`
	AsyncEvent           int32            `protobuf:"varint,13,opt,name=asyncEvent,proto3" json:"asyncEvent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PSpanEvent) Reset()         { *m = PSpanEvent{} }
func (m *PSpanEvent) String() string { return proto.CompactTextString(m) }
func (*PSpanEvent) ProtoMessage()    {}
func (*PSpanEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_72a7884ce2d4c43e, []int{6}
}

func (m *PSpanEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PSpanEvent.Unmarshal(m, b)
}
func (m *PSpanEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PSpanEvent.Marshal(b, m, deterministic)
}
func (m *PSpanEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PSpanEvent.Merge(m, src)
}
func (m *PSpanEvent) XXX_Size() int {
	return xxx_messageInfo_PSpanEvent.Size(m)
}
func (m *PSpanEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_PSpanEvent.DiscardUnknown(m)
}

var xxx_messageInfo_PSpanEvent proto.InternalMessageInfo

func (m *PSpanEvent) GetSequence() int32 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *PSpanEvent) GetDepth() int32 {
	if m != nil {
		return m.Depth
	}
	return 0
}

func (m *PSpanEvent) GetStartElapsed() int32 {
	if m != nil {
		return m.StartElapsed
	}
	return 0
}

func (m *PSpanEvent) GetEndElapsed() int32 {
	if m != nil {
		return m.EndElapsed
	}
	return 0
}

func (m *PSpanEvent) GetServiceType() int32 {
	if m != nil {
		return m.ServiceType
	}
	return 0
}

func (m *PSpanEvent) GetAnnotation() []*PAnnotation {
	if m != nil {
		return m.Annotation
	}
	return nil
}

func (m *PSpanEvent) GetApiId() int32 {
	if m != nil {
		return m.ApiId
	}
	return 0
}

func (m *PSpanEvent) GetExceptionInfo() *PIntStringValue {
	if m != nil {
		return m.ExceptionInfo
	}
	return nil
}

func (m *PSpanEvent) GetNextEvent() *PNextEvent {
	if m != nil {
		return m.NextEvent
	}
	return nil
}

func (m *PSpanEvent) GetAsyncEvent() int32 {
	if m != nil {
		return m.AsyncEvent
	}
	return 0
}

type PNextEvent struct {
	// Types that are valid to be assigned to Field:
	//	*PNextEvent_MessageEvent
	Field                isPNextEvent_Field `protobuf_oneof:"field"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *PNextEvent) Reset()         { *m = PNextEvent{} }
func (m *PNextEvent) String() string { return proto.CompactTextString(m) }
func (*PNextEvent) ProtoMessage()    {}
func (*PNextEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_72a7884ce2d4c43e, []int{7}
}

func (m *PNextEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PNextEvent.Unmarshal(m, b)
}
func (m *PNextEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PNextEvent.Marshal(b, m, deterministic)
}
func (m *PNextEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PNextEvent.Merge(m, src)
}
func (m *PNextEvent) XXX_Size() int {
	return xxx_messageInfo_PNextEvent.Size(m)
}
func (m *PNextEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_PNextEvent.DiscardUnknown(m)
}

var xxx_messageInfo_PNextEvent proto.InternalMessageInfo

type isPNextEvent_Field interface {
	isPNextEvent_Field()
}

type PNextEvent_MessageEvent struct {
	MessageEvent *PMessageEvent `protobuf:"bytes,1,opt,name=messageEvent,proto3,oneof"`
}

func (*PNextEvent_MessageEvent) isPNextEvent_Field() {}

func (m *PNextEvent) GetField() isPNextEvent_Field {
	if m != nil {
		return m.Field
	}
	return nil
}

func (m *PNextEvent) GetMessageEvent() *PMessageEvent {
	if x, ok := m.GetField().(*PNextEvent_MessageEvent); ok {
		return x.MessageEvent
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*PNextEvent) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*PNextEvent_MessageEvent)(nil),
	}
}

type PMessageEvent struct {
	NextSpanId           int64    `protobuf:"fixed64,1,opt,name=nextSpanId,proto3" json:"nextSpanId,omitempty"`
	EndPoint             string   `protobuf:"bytes,2,opt,name=endPoint,proto3" json:"endPoint,omitempty"`
	DestinationId        string   `protobuf:"bytes,3,opt,name=destinationId,proto3" json:"destinationId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PMessageEvent) Reset()         { *m = PMessageEvent{} }
func (m *PMessageEvent) String() string { return proto.CompactTextString(m) }
func (*PMessageEvent) ProtoMessage()    {}
func (*PMessageEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_72a7884ce2d4c43e, []int{8}
}

func (m *PMessageEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PMessageEvent.Unmarshal(m, b)
}
func (m *PMessageEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PMessageEvent.Marshal(b, m, deterministic)
}
func (m *PMessageEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PMessageEvent.Merge(m, src)
}
func (m *PMessageEvent) XXX_Size() int {
	return xxx_messageInfo_PMessageEvent.Size(m)
}
func (m *PMessageEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_PMessageEvent.DiscardUnknown(m)
}

var xxx_messageInfo_PMessageEvent proto.InternalMessageInfo

func (m *PMessageEvent) GetNextSpanId() int64 {
	if m != nil {
		return m.NextSpanId
	}
	return 0
}

func (m *PMessageEvent) GetEndPoint() string {
	if m != nil {
		return m.EndPoint
	}
	return ""
}

func (m *PMessageEvent) GetDestinationId() string {
	if m != nil {
		return m.DestinationId
	}
	return ""
}

type PSpanChunk struct {
	Version                int32           `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	TransactionId          *PTransactionId `protobuf:"bytes,2,opt,name=transactionId,proto3" json:"transactionId,omitempty"`
	SpanId                 int64           `protobuf:"fixed64,3,opt,name=spanId,proto3" json:"spanId,omitempty"`
	EndPoint               string          `protobuf:"bytes,4,opt,name=endPoint,proto3" json:"endPoint,omitempty"`
	SpanEvent              []*PSpanEvent   `protobuf:"bytes,5,rep,name=spanEvent,proto3" json:"spanEvent,omitempty"`
	ApplicationServiceType int32           `protobuf:"varint,6,opt,name=applicationServiceType,proto3" json:"applicationServiceType,omitempty"`
	KeyTime                int64           `protobuf:"varint,7,opt,name=keyTime,proto3" json:"keyTime,omitempty"`
	LocalAsyncId           *PLocalAsyncId  `protobuf:"bytes,8,opt,name=localAsyncId,proto3" json:"localAsyncId,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}        `json:"-"`
	XXX_unrecognized       []byte          `json:"-"`
	XXX_sizecache          int32           `json:"-"`
}

func (m *PSpanChunk) Reset()         { *m = PSpanChunk{} }
func (m *PSpanChunk) String() string { return proto.CompactTextString(m) }
func (*PSpanChunk) ProtoMessage()    {}
func (*PSpanChunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_72a7884ce2d4c43e, []int{9}
}

func (m *PSpanChunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PSpanChunk.Unmarshal(m, b)
}
func (m *PSpanChunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PSpanChunk.Marshal(b, m, deterministic)
}
func (m *PSpanChunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PSpanChunk.Merge(m, src)
}
func (m *PSpanChunk) XXX_Size() int {
	return xxx_messageInfo_PSpanChunk.Size(m)
}
func (m *PSpanChunk) XXX_DiscardUnknown() {
	xxx_messageInfo_PSpanChunk.DiscardUnknown(m)
}

var xxx_messageInfo_PSpanChunk proto.InternalMessageInfo

func (m *PSpanChunk) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *PSpanChunk) GetTransactionId() *PTransactionId {
	if m != nil {
		return m.TransactionId
	}
	return nil
}

func (m *PSpanChunk) GetSpanId() int64 {
	if m != nil {
		return m.SpanId
	}
	return 0
}

func (m *PSpanChunk) GetEndPoint() string {
	if m != nil {
		return m.EndPoint
	}
	return ""
}

func (m *PSpanChunk) GetSpanEvent() []*PSpanEvent {
	if m != nil {
		return m.SpanEvent
	}
	return nil
}

func (m *PSpanChunk) GetApplicationServiceType() int32 {
	if m != nil {
		return m.ApplicationServiceType
	}
	return 0
}

func (m *PSpanChunk) GetKeyTime() int64 {
	if m != nil {
		return m.KeyTime
	}
	return 0
}

func (m *PSpanChunk) GetLocalAsyncId() *PLocalAsyncId {
	if m != nil {
		return m.LocalAsyncId
	}
	return nil
}

type PResult struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PResult) Reset()         { *m = PResult{} }
func (m *PResult) String() string { return proto.CompactTextString(m) }
func (*PResult) ProtoMessage()    {}
func (*PResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_72a7884ce2d4c43e, []int{10}
}

func (m *PResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PResult.Unmarshal(m, b)
}
func (m *PResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PResult.Marshal(b, m, deterministic)
}
func (m *PResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PResult.Merge(m, src)
}
func (m *PResult) XXX_Size() int {
	return xxx_messageInfo_PResult.Size(m)
}
func (m *PResult) XXX_DiscardUnknown() {
	xxx_messageInfo_PResult.DiscardUnknown(m)
}

var xxx_messageInfo_PResult proto.InternalMessageInfo

func (m *PResult) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *PResult) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type PSqlMetaData struct {
	SqlId                int32    `protobuf:"varint,1,opt,name=sqlId,proto3" json:"sqlId,omitempty"`
	Sql                  string   `protobuf:"bytes,2,opt,name=sql,proto3" json:"sql,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PSqlMetaData) Reset()         { *m = PSqlMetaData{} }
func (m *PSqlMetaData) String() string { return proto.CompactTextString(m) }
func (*PSqlMetaData) ProtoMessage()    {}
func (*PSqlMetaData) Descriptor() ([]byte, []int) {
	return fileDescriptor_72a7884ce2d4c43e, []int{11}
}

func (m *PSqlMetaData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PSqlMetaData.Unmarshal(m, b)
}
func (m *PSqlMetaData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PSqlMetaData.Marshal(b, m, deterministic)
}
func (m *PSqlMetaData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PSqlMetaData.Merge(m, src)
}
func (m *PSqlMetaData) XXX_Size() int {
	return xxx_messageInfo_PSqlMetaData.Size(m)
}
func (m *PSqlMetaData) XXX_DiscardUnknown() {
	xxx_messageInfo_PSqlMetaData.DiscardUnknown(m)
}

var xxx_messageInfo_PSqlMetaData proto.InternalMessageInfo

func (m *PSqlMetaData) GetSqlId() int32 {
	if m != nil {
		return m.SqlId
	}
	return 0
}

func (m *PSqlMetaData) GetSql() string {
	if m != nil {
		return m.Sql
	}
	return ""
}

type PApiMetaData struct {
	ApiId                int32    `protobuf:"varint,1,opt,name=apiId,proto3" json:"apiId,omitempty"`
	ApiInfo              string   `protobuf:"bytes,2,opt,name=apiInfo,proto3" json:"apiInfo,omitempty"`
	Line                 int32    `protobuf:"varint,3,opt,name=line,proto3" json:"line,omitempty"`
	Type                 int32    `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PApiMetaData) Reset()         { *m = PApiMetaData{} }
func (m *PApiMetaData) String() string { return proto.CompactTextString(m) }
func (*PApiMetaData) ProtoMessage()    {}
func (*PApiMetaData) Descriptor() ([]byte, []int) {
	return fileDescriptor_72a7884ce2d4c43e, []int{12}
}

func (m *PApiMetaData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PApiMetaData.Unmarshal(m, b)
}
func (m *PApiMetaData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PApiMetaData.Marshal(b, m, deterministic)
}
func (m *PApiMetaData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PApiMetaData.Merge(m, src)
}
func (m *PApiMetaData) XXX_Size() int {
	return xxx_messageInfo_PApiMetaData.Size(m)
}
func (m *PApiMetaData) XXX_DiscardUnknown() {
	xxx_messageInfo_PApiMetaData.DiscardUnknown(m)
}

var xxx_messageInfo_PApiMetaData proto.InternalMessageInfo

func (m *PApiMetaData) GetApiId() int32 {
	if m != nil {
		return m.ApiId
	}
	return 0
}

func (m *PApiMetaData) GetApiInfo() string {
	if m != nil {
		return m.ApiInfo
	}
	return ""
}

func (m *PApiMetaData) GetLine() int32 {
	if m != nil {
		return m.Line
	}
	return 0
}

func (m *PApiMetaData) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

type PStringMetaData struct {
	StringId             int32    `protobuf:"varint,1,opt,name=stringId,proto3" json:"stringId,omitempty"`
	StringValue          string   `protobuf:"bytes,2,opt,name=stringValue,proto3" json:"stringValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PStringMetaData) Reset()         { *m = PStringMetaData{} }
func (m *PStringMetaData) String() string { return proto.CompactTextString(m) }
func (*PStringMetaData) ProtoMessage()    {}
func (*PStringMetaData) Descriptor() ([]byte, []int) {
	return fileDescriptor_72a7884ce2d4c43e, []int{13}
}

func (m *PStringMetaData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PStringMetaData.Unmarshal(m, b)
}
func (m *PStringMetaData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PStringMetaData.Marshal(b, m, deterministic)
}
func (m *PStringMetaData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PStringMetaData.Merge(m, src)
}
func (m *PStringMetaData) XXX_Size() int {
	return xxx_messageInfo_PStringMetaData.Size(m)
}
func (m *PStringMetaData) XXX_DiscardUnknown() {
	xxx_messageInfo_PStringMetaData.DiscardUnknown(m)
}

var xxx_messageInfo_PStringMetaData proto.InternalMessageInfo

func (m *PStringMetaData) GetStringId() int32 {
	if m != nil {
		return m.StringId
	}
	return 0
}

func (m *PStringMetaData) GetStringValue() string {
	if m != nil {
		return m.StringValue
	}
	return ""
}

func init() {
	proto.RegisterType((*PSpanMessage)(nil), "v1.PSpanMessage")
	proto.RegisterType((*PSpan)(nil), "v1.PSpan")
	proto.RegisterType((*PTransactionId)(nil), "v1.PTransactionId")
	proto.RegisterType((*PAcceptEvent)(nil), "v1.PAcceptEvent")
	proto.RegisterType((*PParentInfo)(nil), "v1.PParentInfo")
	proto.RegisterType((*PLocalAsyncId)(nil), "v1.PLocalAsyncId")
	proto.RegisterType((*PSpanEvent)(nil), "v1.PSpanEvent")
	proto.RegisterType((*PNextEvent)(nil), "v1.PNextEvent")
	proto.RegisterType((*PMessageEvent)(nil), "v1.PMessageEvent")
	proto.RegisterType((*PSpanChunk)(nil), "v1.PSpanChunk")
	proto.RegisterType((*PResult)(nil), "v1.PResult")
	proto.RegisterType((*PSqlMetaData)(nil), "v1.PSqlMetaData")
	proto.RegisterType((*PApiMetaData)(nil), "v1.PApiMetaData")
	proto.RegisterType((*PStringMetaData)(nil), "v1.PStringMetaData")
}

func init() {
	proto.RegisterFile("Span.proto", fileDescriptor_72a7884ce2d4c43e)
}

var fileDescriptor_72a7884ce2d4c43e = []byte{
	// 991 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0x5f, 0x6f, 0xe3, 0x44,
	0x10, 0x3f, 0xe7, 0x6f, 0x33, 0x49, 0xda, 0xdc, 0x02, 0x27, 0xab, 0x20, 0x08, 0x16, 0x42, 0x79,
	0x38, 0xa5, 0x5c, 0x81, 0x03, 0x1e, 0x78, 0x48, 0xa1, 0x52, 0x23, 0xd1, 0x12, 0x6d, 0x2a, 0xde,
	0xf7, 0xec, 0x8d, 0x6b, 0x9d, 0xb3, 0xde, 0xd8, 0x9b, 0xe8, 0xfa, 0x21, 0xf8, 0x08, 0x7c, 0x22,
	0x3e, 0x0a, 0xaf, 0x7c, 0x00, 0xb4, 0xb3, 0x6b, 0x7b, 0x5d, 0x7a, 0x77, 0x3c, 0xf1, 0x94, 0x9d,
	0xdf, 0xcc, 0xec, 0x8c, 0xe7, 0xcf, 0x6f, 0x03, 0xb0, 0x96, 0x4c, 0xcc, 0x65, 0x9e, 0xa9, 0x8c,
	0xb4, 0x0e, 0x2f, 0x4e, 0x3f, 0x8e, 0xb3, 0x2c, 0x4e, 0xf9, 0x19, 0x22, 0xaf, 0xf6, 0x9b, 0x33,
	0xbe, 0x95, 0xea, 0xde, 0x18, 0x9c, 0x4e, 0x16, 0x42, 0x64, 0x8a, 0xa9, 0x24, 0xb3, 0x2e, 0xc1,
	0x1d, 0x8c, 0x56, 0xfa, 0x86, 0x6b, 0x5e, 0x14, 0x2c, 0xe6, 0xe4, 0x33, 0xe8, 0x14, 0x92, 0x09,
	0xdf, 0x9b, 0x7a, 0xb3, 0xe1, 0xf9, 0x60, 0x7e, 0x78, 0x31, 0x47, 0xfd, 0xd5, 0x13, 0x8a, 0x0a,
	0x32, 0x87, 0x81, 0xfe, 0xfd, 0xe9, 0x6e, 0x2f, 0x5e, 0xfb, 0x2d, 0xb4, 0x3a, 0xae, 0xac, 0x10,
	0xbd, 0x7a, 0x42, 0x6b, 0x93, 0x8b, 0x3e, 0x74, 0x37, 0x09, 0x4f, 0xa3, 0xe0, 0xaf, 0x0e, 0x74,
	0xd1, 0x88, 0xf8, 0xd0, 0x3f, 0xf0, 0xbc, 0x48, 0x32, 0x13, 0xa6, 0x4b, 0x4b, 0x91, 0x7c, 0x0f,
	0x63, 0x95, 0x33, 0x51, 0xb0, 0x50, 0xa7, 0xb8, 0x8c, 0x6c, 0x00, 0x82, 0x01, 0x6e, 0x5d, 0x0d,
	0x6d, 0x1a, 0x92, 0x67, 0xd0, 0xd3, 0x31, 0x97, 0x91, 0xdf, 0x9e, 0x7a, 0xb3, 0x09, 0xb5, 0x12,
	0x09, 0x60, 0x24, 0x59, 0xce, 0x85, 0x5a, 0x1b, 0x6d, 0x07, 0xb5, 0x0d, 0x8c, 0x7c, 0x02, 0x83,
	0x42, 0xb1, 0x5c, 0xdd, 0x26, 0x5b, 0xee, 0x77, 0xa7, 0xde, 0xac, 0x4d, 0x6b, 0x40, 0x67, 0xcb,
	0x53, 0x26, 0x0b, 0x1e, 0xf9, 0x3d, 0x93, 0xad, 0x15, 0xc9, 0x87, 0xd0, 0x65, 0x32, 0x59, 0x46,
	0x7e, 0x1f, 0x71, 0x23, 0x90, 0x29, 0x0c, 0x0b, 0x9e, 0x1f, 0x92, 0x90, 0xdf, 0xde, 0x4b, 0xee,
	0x1f, 0xa1, 0xce, 0x85, 0xc8, 0x39, 0x0c, 0x59, 0x18, 0x72, 0xa9, 0x2e, 0x0f, 0x5c, 0x28, 0x7f,
	0x80, 0xdf, 0x38, 0xc1, 0x6f, 0x5c, 0xd4, 0x38, 0x75, 0x8d, 0xc8, 0x19, 0x00, 0xab, 0x7a, 0xe7,
	0xc3, 0xb4, 0x3d, 0x1b, 0x9e, 0x9f, 0x18, 0x97, 0x0a, 0xa6, 0x8e, 0x09, 0x21, 0xd0, 0xd9, 0xa4,
	0x2c, 0xf6, 0x87, 0x18, 0x1f, 0xcf, 0x64, 0x02, 0x6d, 0x9e, 0xe7, 0xfe, 0x68, 0xea, 0xcd, 0x9e,
	0x52, 0x7d, 0x24, 0xcf, 0x4d, 0x37, 0x4d, 0x22, 0x63, 0xbc, 0xb5, 0xee, 0xa6, 0x49, 0xa3, 0x36,
	0x20, 0x3f, 0xc0, 0x98, 0xbf, 0xd1, 0x39, 0xe9, 0x9a, 0x8b, 0x4d, 0xe6, 0x1f, 0x63, 0xea, 0x1f,
	0xa0, 0xc7, 0x52, 0xa8, 0xb5, 0xca, 0x13, 0x11, 0xff, 0xc6, 0xd2, 0x3d, 0xa7, 0x4d, 0x4b, 0xf2,
	0x12, 0x9e, 0x31, 0x29, 0xd3, 0x24, 0xc4, 0xec, 0xd6, 0x4e, 0x81, 0x4e, 0x30, 0xc1, 0xb7, 0x68,
	0xb5, 0x5f, 0x9a, 0xc5, 0x71, 0x22, 0x62, 0xb7, 0xfd, 0x3a, 0xf6, 0xc4, 0xf8, 0x3d, 0xae, 0x0d,
	0x04, 0x1c, 0x37, 0x07, 0x46, 0xf7, 0x91, 0xc5, 0x5c, 0xa8, 0x65, 0x84, 0x53, 0x37, 0xa0, 0xa5,
	0x48, 0xbe, 0x84, 0x63, 0x3c, 0xae, 0xab, 0x21, 0x68, 0xe1, 0x10, 0x3c, 0x40, 0xc9, 0x29, 0x1c,
	0x15, 0x7c, 0xb7, 0xe7, 0x22, 0xe4, 0x38, 0x65, 0x6d, 0x5a, 0xc9, 0xc1, 0xef, 0x1e, 0x8c, 0xdc,
	0xee, 0xe9, 0x5a, 0xe7, 0x32, 0xb4, 0xa1, 0xf4, 0x51, 0xbb, 0x73, 0x11, 0xad, 0xb2, 0x44, 0x28,
	0x0c, 0x30, 0xa0, 0x95, 0x4c, 0x3e, 0x05, 0xc8, 0xf9, 0x36, 0x53, 0x7c, 0x11, 0x45, 0x39, 0x5e,
	0x3e, 0xa0, 0x0e, 0xa2, 0xdb, 0x6f, 0x46, 0x16, 0x3f, 0xbd, 0x83, 0x65, 0x37, 0xed, 0x5f, 0x55,
	0x30, 0x75, 0x4c, 0x82, 0x3f, 0x3c, 0x18, 0x3a, 0x3a, 0xf2, 0x0d, 0x7c, 0x64, 0xb4, 0x8b, 0xba,
	0xce, 0x37, 0x6c, 0xcb, 0x6d, 0x82, 0x8f, 0x2b, 0x1f, 0xf5, 0xc2, 0xa6, 0xb5, 0xb0, 0xf8, 0x8f,
	0x2b, 0xf5, 0xce, 0x99, 0xd1, 0xcd, 0xf2, 0xab, 0xac, 0x50, 0xf6, 0x73, 0x1a, 0x58, 0x70, 0x09,
	0xe3, 0xd5, 0x2f, 0x59, 0xc8, 0xd2, 0x45, 0x71, 0x2f, 0x42, 0xdb, 0x1e, 0x73, 0x2c, 0x49, 0xc1,
	0x8a, 0x8d, 0xb2, 0x9b, 0xb8, 0x75, 0xd9, 0xff, 0x6e, 0x01, 0xd4, 0xb3, 0xda, 0x30, 0xf5, 0x9a,
	0xa6, 0x7a, 0x5b, 0x23, 0x2e, 0xd5, 0x9d, 0xbd, 0xc3, 0x08, 0x3a, 0x57, 0x5c, 0xf5, 0x4b, 0xbb,
	0xe2, 0x6d, 0x54, 0x36, 0x30, 0xdd, 0x1c, 0x2e, 0xa2, 0xd2, 0xa2, 0x83, 0x16, 0x0e, 0xf2, 0x70,
	0xe3, 0xbb, 0xb8, 0x5e, 0x8d, 0x8d, 0x6f, 0x6e, 0x6f, 0xef, 0xfd, 0xdb, 0x5b, 0x51, 0x0b, 0xe0,
	0x65, 0x96, 0x5a, 0xfe, 0xb5, 0x7f, 0xc3, 0xff, 0xbc, 0x7f, 0xcf, 0x61, 0x20, 0xf8, 0x1b, 0xcb,
	0x38, 0x23, 0x87, 0xb6, 0x6f, 0x4a, 0x94, 0xd6, 0x06, 0xfa, 0x8b, 0xb1, 0xfa, 0x25, 0x2f, 0xe0,
	0x17, 0xd7, 0x48, 0x70, 0x03, 0x50, 0x3b, 0x92, 0xef, 0x60, 0xb4, 0x35, 0xcf, 0x87, 0xb1, 0x37,
	0x6f, 0xc7, 0x53, 0xbc, 0xfe, 0xda, 0x51, 0x5c, 0x3d, 0xa1, 0x0d, 0xc3, 0xfa, 0x6d, 0xd8, 0xc1,
	0xb8, 0x61, 0xa9, 0x13, 0xd0, 0xd9, 0x58, 0xd2, 0xf6, 0x90, 0xb4, 0x1d, 0xe4, 0x9d, 0xbb, 0xf4,
	0x05, 0x8c, 0x23, 0x5e, 0xa8, 0x44, 0x30, 0xfb, 0x88, 0x98, 0xf9, 0x6b, 0x82, 0xc1, 0x9f, 0xe5,
	0xe4, 0xe0, 0x33, 0xf5, 0xbf, 0xbe, 0x49, 0x6e, 0xf2, 0x9d, 0x07, 0xc9, 0x37, 0x08, 0xb9, 0xfb,
	0x3e, 0x42, 0x7e, 0x3b, 0xab, 0xf6, 0xde, 0xc9, 0xaa, 0x3e, 0xf4, 0x5f, 0xf3, 0x7b, 0xa4, 0xba,
	0x3e, 0x12, 0x59, 0x29, 0x92, 0x6f, 0x61, 0x94, 0x3a, 0x6b, 0x89, 0xcf, 0x57, 0xd9, 0x4b, 0x77,
	0x5f, 0x69, 0xc3, 0x2c, 0xf8, 0x11, 0xfa, 0x2b, 0xca, 0x8b, 0x7d, 0xaa, 0xf4, 0xdd, 0xc5, 0x3e,
	0x0c, 0x79, 0x51, 0x60, 0x25, 0x8f, 0x68, 0x29, 0x6a, 0x8d, 0x6d, 0xbf, 0xed, 0x59, 0x29, 0x06,
	0x2f, 0xf5, 0xbf, 0x90, 0x5d, 0x7a, 0xcd, 0x15, 0xfb, 0x99, 0x29, 0xa6, 0xc7, 0xbf, 0xd8, 0xa5,
	0x15, 0x15, 0x18, 0x41, 0x53, 0x6a, 0xb1, 0x4b, 0xad, 0xaf, 0x3e, 0x06, 0x1b, 0x4d, 0xba, 0x32,
	0x71, 0xfd, 0xcc, 0xda, 0x78, 0xee, 0x8b, 0xac, 0xa9, 0x45, 0x26, 0xb8, 0x30, 0x36, 0xae, 0x15,
	0xf5, 0x23, 0x99, 0x26, 0x82, 0xdb, 0xad, 0xc7, 0xb3, 0xc6, 0x94, 0xae, 0xa0, 0xd9, 0x73, 0x3c,
	0x07, 0xbf, 0xc2, 0xc9, 0xca, 0x2c, 0x57, 0x15, 0x4a, 0x53, 0x0d, 0x22, 0x55, 0xb4, 0x4a, 0x46,
	0x42, 0xa8, 0x57, 0xd1, 0x06, 0x75, 0xa1, 0x8b, 0xaf, 0xe0, 0xf3, 0x30, 0xdb, 0xce, 0x05, 0x3b,
	0xf0, 0x3c, 0xcc, 0x72, 0x39, 0x97, 0x89, 0x90, 0x7a, 0x00, 0xe6, 0x71, 0x2e, 0xc3, 0xb9, 0xca,
	0x59, 0xc8, 0x2f, 0x06, 0xba, 0xe7, 0x2b, 0xfd, 0x37, 0x6d, 0xe5, 0xbd, 0xea, 0xe1, 0xff, 0xb5,
	0xaf, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0xad, 0xc2, 0x70, 0xff, 0xf0, 0x09, 0x00, 0x00,
}
