name: publish-pypitest

on: [workflow_dispatch]

jobs:
  pinpointPy-manylinux2014_x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - uses: aminya/setup-cpp@v0.20.1
        with:
          cmake: true
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twine wheel
      - name: package
        run: |
          rm setup.py
          ln -s setup_pypi_test.py setup.py
          python setup.py sdist bdist_wheel
          twine check dist/*
      - name: Publish package to pypitest
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.EELIUTEST }}
          repository_url: https://test.pypi.org/legacy/
  # pinpointPy-macosx_10_15_x86_64.whl: