name: publish

on: 
  release:
    types: [workflow_dispatch]
  workflow_dispatch:

jobs:
  collector-agent:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the collector-agent Docker image
      run: |
        docker build collector-agent --tag ghcr.io/$GITHUB_REPOSITORY/collector-agent:latest
        docker push ghcr.io/$GITHUB_REPOSITORY/collector-agent:latest