name: publish-test

on: [workflow_dispatch]

jobs:
  pinpointPy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twine
      - name: package
        run: |
          rm setup.py
          ln -s setup_pypi_test.py setup.py
          python setup.py sdist
          twine check dist/*
      - name: Publish package to pypitest
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.EELIUTEST }}
          repository_url: https://test.pypi.org/legacy/
