name: publish-collector-agent

on: 
  release:
    types: [workflow_dispatch]
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'
jobs:
  collector-agent:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the collector-agent Docker image
      run: |
        IMAGE_NAME=collector-agent
        IMAGE_TAG=$(echo "${GITHUB_REF##*/} " | sed -e 's,.*/\(.*\),\1,')
        IMAGE_ID=ghcr.io/$GITHUB_REPOSITORY

        docker build --pull --no-cache . --file collector-agent/Dockerfile --tag $IMAGE_NAME

        docker tag $IMAGE_NAME $IMAGE_ID/$IMAGE_NAME:$IMAGE_TAG
        docker tag $IMAGE_NAME $IMAGE_ID/$IMAGE_NAME:latest
        docker push --all-tags $IMAGE_ID/$IMAGE_NAME